-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.activision
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    activision_code character varying NOT NULL,
    is_activited boolean NOT NULL,
    is_a_mernis_activated boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activision_for_employer
(
    activision_for_employer_id integer NOT NULL,
    id_for_employers integer NOT NULL,
    is_a_staff_approval boolean NOT NULL,
    PRIMARY KEY (activision_for_employer_id)
);

CREATE TABLE public."activision_for_job_seekers "
(
    activision_for_job_seekers_id integer NOT NULL,
    job_positions_for_job_seekers integer NOT NULL,
    PRIMARY KEY (activision_for_job_seekers_id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
    company_name character varying NOT NULL,
    web_site character varying NOT NULL,
    phone_number character varying NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_position_name character varying NOT NULL,
    "position" character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    job_seekers_id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    nationality_id character varying(11) NOT NULL,
    birthday_day date NOT NULL,
    PRIMARY KEY (job_seekers_id)
);

CREATE TABLE public.system_staffs
(
    system_staff_id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    PRIMARY KEY (system_staff_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    e_mail character varying(50) NOT NULL,
    password character varying NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.activision_for_employer
    ADD FOREIGN KEY (activision_for_employer_id)
    REFERENCES public.activision (id)
    NOT VALID;


ALTER TABLE public.activision_for_employer
    ADD FOREIGN KEY (activision_for_employer_id)
    REFERENCES public.employers (employer_id)
    NOT VALID;


ALTER TABLE public."activision_for_job_seekers "
    ADD FOREIGN KEY (activision_for_job_seekers_id)
    REFERENCES public.activision (id)
    NOT VALID;


ALTER TABLE public."activision_for_job_seekers "
    ADD FOREIGN KEY (activision_for_job_seekers_id)
    REFERENCES public.job_seekers (job_seekers_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (job_seekers_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_staffs
    ADD FOREIGN KEY (system_staff_id)
    REFERENCES public.users (id)
    NOT VALID;

END;